### ISSUE TITLE
Email sub button mobile

### ISSUE THREAD

**Issue by charlesjdillon** [washingtonstateuniversity/news.wsu.edu-internal#66]
May I suggest putting the margin on the input box and not the button instead. This will prevent weird alignment on the button during mobile. 
![screen shot 2017-12-18 at 1 38 30 pm](https://user-images.githubusercontent.com/4007184/34129389-d54dbe9e-e3f8-11e7-8a71-a621042bc3fc.png)

**Comment by jeremyfelt** [comment]
@slocker3 I think this was fixed during the latest changes, yeah?

**Comment by jeremyfelt** [comment]
Things look good on mobile for me right now.
